### PR TITLE
Fix AOF rewrite and restore BF tests

### LINKED ISSUE #74: AOF related integration tests failing for branch 1.0 and unstable
When I run `./build.sh`, I see the following tests are failing

```
tests/test_bloom_aofrewrite.py::TestBloomAofRewrite::test_basic_aofrewrite_and_restore[random-seed]
tests/test_bloom_aofrewrite.py::TestBloomAofRewrite::test_basic_aofrewrite_and_restore[fixed-seed] tests/test_bloom_aofrewrite.py::TestBloomAofRewrite::test_aofrewrite_bloomfilter_metrics[random-seed]
tests/test_bloom_aofrewrite.py::TestBloomAofRewrite::test_aofrewrite_bloomfilter_metrics[fixed-seed]
```

Also, I see there are some indentation errors that are leading to failures in tests.

### PR DESCRIPTION
**Pull request by arpitbbhayani**
The AOF rewrite tests were failing because bloom filter data was not being properly restored after server restart. The root cause was twofold:

1. BF.LOAD command was replicating during AOF loading, causing duplicate entries
2. Tests were not properly configuring AOF persistence for server restart

Changes:
- Modified BF.LOAD handler to skip replication when loading from AOF by checking must_obey_client() context
- Updated AOF tests to enable appendonly before adding data
- Added wait for initial AOF rewrite to prevent concurrent rewrites
- Set appendonly in server startup args for proper AOF loading on restart

Also includes minor fixes:
- Changed build.sh shebang to bash for better compatibility
- Updated pytest requirement to 7.4.3
- Fixed indentation in utils.rs documentation

Fixes #74

### CODE REVIEW

File: src/bloom/command_handler.rs [hunk 1]
```diff
@@ -817,24 +817,33 @@ pub fn bloom_filter_load(ctx: &Context, input_args: &[ValkeyString]) -> ValkeyRe
         None => {
             // if filter not exists, create it.
             let hex = value.to_vec();
-            let validate_size_limit = !must_obey_client(ctx);
+            let is_aof_loading = must_obey_client(ctx);
```
Comment (zackcam) [inline src/bloom/command_handler.rs]: Do we need this intermediary step here of having the variable of `is_aof_loading` could we not use `validate_size_limit ` on line 829?

**Comment by enjoy-binbin** [comment]
@arpitbbhayani can you fix the DCO?

File: src/bloom/command_handler.rs [hunk 2]
```diff
@@ -817,24 +817,33 @@ pub fn bloom_filter_load(ctx: &Context, input_args: &[ValkeyString]) -> ValkeyRe
...
+                    seed: bloom.seed(),
+                    items: &input_args[idx..],
+                })
+            } else {
+                None
             };
             match filter_key.set_value(&BLOOM_TYPE, bloom) {
                 Ok(_) => {
-                    replicate_and_notify_events(ctx, filter_name, false, true, replicate_args);
+                    // Only replicate if not loading from AOF/replication
```
Comment (KarthikSubbarao) [inline src/bloom/command_handler.rs]: From what I remember reading in the core, calling the ValkeyModule_Replicate Module API in the core has no effect if the role is a replica (if we received it from the replication stream). I would assume it is the same for AOF. Could we check if this is neccesary?

File: src/bloom/command_handler.rs [hunk 3]
```diff
@@ -817,24 +817,33 @@ pub fn bloom_filter_load(ctx: &Context, input_args: &[ValkeyString]) -> ValkeyRe
...
+                    if let Some(args) = replicate_args {
+                        replicate_and_notify_events(ctx, filter_name, false, true, args);
+                    }
```
Comment (KarthikSubbarao) [inline src/bloom/command_handler.rs]: One side effect from this change is that, we only post a notification on bloom object creations on primary nodes. Not on replica nodes

File: src/bloom/command_handler.rs (hunk 1 above)
Comment (arpitbbhayani) [reply src/bloom/command_handler.rs]: I went through the code and realized we do not need this change. I wrongly analyzed the flow, but now I have reverted the change and validated the flow.

File: src/bloom/command_handler.rs (hunk 2 above)
Comment (arpitbbhayani) [reply src/bloom/command_handler.rs]: Yes. I went though the code and understood the flow end-to-end and realized this was a redundant check. given that it passed the test I thought this is needed. Now, I have reverted this change. thanks.

File: src/bloom/command_handler.rs (hunk 3 above)
Comment (arpitbbhayani) [reply src/bloom/command_handler.rs]: yup. removed this change. ref comment above.

**Comment by arpitbbhayani** [comment]
Thank you so much for reviewing the code. Apologies that it took some time for me to come back.
I have addressed all the concerns and made the changes.

Now, the PR only fixes the AOF tests that were failing and other changes have been reverted.

File: build.sh [hunk 4]
```diff
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/bin/bash
```
Comment (KarthikSubbarao) [inline build.sh]: Suggesting we retain `#!/usr/bin/env sh` for better compatibility 

```suggestion
#!/usr/bin/env sh
```

**Comment by KarthikSubbarao** [comment]
Thank you for your help with this PR, @arpitbbhayani :D
